[package]
name = "reality-module"
version = "0.1.0"
edition = "2024"

[dependencies]
reality-ast = { path = "../reality-ast" }
reality-error = { path = "../reality-error" }
reality-parser = { path = "../reality-parser" }
